// ─────────────────────────────────────────────
// Preset Packages & Custom Category Menus Data
// ─────────────────────────────────────────────

export const TIFFIN_MENUS = {
  "Tiffin 1": ["Sweet Kesari", "Idli", "Rava Upma", "Sambar", "Coconut Chutney"],
  "Tiffin 2": ["Semiya Kesari", "Poori", "Urulai masala", "Pongal", "Sambar", "Chutney (2 types)"],
  "Tiffin 3": ["Pineapple pudding", "Medhu vadai", "Idli", "Pongal", "Sambar", "Chutney (2 types)"],
  "Tiffin 4": ["Gulab jamun", "Medu vadai", "Idli", "Semiya Sewai", "Khichadi", "Sambar", "Chutney (2 types)"],
  "Tiffin 5": ["Akkaravadisal", "Medhu vadai", "Pongal", "Chapati", "Chana masala", "Idli", "Sambar", "Chutney (2 types)"],
  "Tiffin 6": ["Carrot halwa", "Medhu vadai", "Rava idli", "Onion uthappam", "Pongal", "Poori", "Urulai masala", "Sambar", "Chutney (2 types)"],
  "Tiffin 7": ["Kaju Katli", "Medhu vadai", "Poori", "Vada curry", "Podi dosai", "Thattu idli", "Idiyappam", "Sambar", "Chutney (2 types)"],
  "Tiffin 8": ["Ashoka halwa", "Medhu vadai", "Chapati", "Chana masala", "Heartin Idli", "Khichadi", "Podi uthappam", "Sambar", "Chutney (2 types)"],
  "Tiffin 9": ["Wheat halwa", "Medhu vadai", "Idiyappam", "Kuruma", "Malli", "Malli Idli", "Semiya Sewai", "Sambar", "Chutney (2 types)"],
  "Tiffin 10": ["Tuti fruiti Kesari", "Medhu vadai", "Poori", "Chana masala", "Khushboo Idli", "Pesarot Dosai", "Pongal", "Sambar", "Chutney (2 types)"],
  "Tiffin 11": ["TutiFruti Kesari", "Medhu Vadai", "Idli", "Pongal", "Rava Khichadi", "Chutney (2 types)", "Tiffin Sambar", "Coffee"],
  "Tiffin 12": ["Ashoka Halwa", "Special Vadai", "Poori", "Chana Masala", "Malli Idli", "Rava khichadi", "Masaldosai", "Chutney (2 types)", "Sambar", "Coffee"],
  "Tiffin 13": ["Pineapple Putting", "Vadai", "Poori", "Potato Masala", "Idli", "Ghee Pongal", "Semiya khichadi", "Chutney (2)", "Tiffin Sambar", "Coffee"],
  "Tiffin 14": ["Ashoka Halwa", "Special Vadai", "Poori", "White Kuruma", "Kanchipuram Idli", "Rava Kichadi", "Masal Dosai", "Chutney (2)", "Sambar", "Coffee"],
  "Tiffin 15": ["Kasi Halwa", "Special Vadai", "Poori", "Chana Masala", "Kanchipuram Idli", "Rava Khichadi", "Onion Uthappam", "Chutney (2)", "Sambar", "Coffee"],
  "Tiffin 16": ["Bread Halwa", "Medhu Vadai", "Idiyappam", "White Kuruma", "Malli Idli", "Ven Pongal", "Masala Dosai", "Sambar", "Chutney (2 varieties)", "Coffee"],
  "Tiffin 17": ["Ashoka Halwa", "Medhu Vadai", "Poori", "Potato Masala", "Heartin Idli", "Podi Dosai", "Ghee Pongal", "Chutney (2 varieties)", "Tiffin Sambar", "Coffee"],
  "Tiffin 18": ["Kasi Halwa", "Medhu Vadai", "Chola Poori", "Chana Masala", "Idiyappam", "Mixed Vegetable Kuruma", "Ghee Mini Idli", "Vegetable Khichadi", "Cashew Pongal", "Chutney (2 varieties)", "Tiffin Sambar", "Coffee"],
  "Tiffin 19": ["Carrot Halwa", "Gulab Jamun", "Onion Medhu Vadai", "Appam", "Coconut Milk", "Mini Poori", "Potato Masala", "Onion Mini Uthappam", "Vada Curry", "Rava Idli", "Chutney (2 varieties)", "Tiffin Sambar", "Coffee"],
  "Tiffin 20": ["Dry Fruit Halwa", "Malpua (Sweet)", "Mini Sambar Vadai", "Appam", "Coconut Milk", "Kuzha Puttu", "Kadala Curry", "Methi Poori", "Mushroom Gravy", "Elaneer Idli", "Rava Pongal", "Carrot Dosai", "Chutney (3 varieties)", "Sambar", "Coffee"]
};

export const LUNCH_MENUS = {
  "Lunch 1": ["White Rice", "Sambar", "Rasam", "Poriyal"],
  "Lunch 2": ["Sweet Payasam", "White Rice", "Sambar", "Rasam", "Buttermilk", "Koottu", "Appalam", "Pickle"],
  "Lunch 3": ["Semiya payasam", "White Rice", "Sambar", "Rasam", "Butter milk", "Varuval", "Vathal", "Appalam", "Pickle"],
  "Lunch 4": ["Kaju Katli", "Masal vadai", "White Rice", "Sambar", "Vatha Kulambu", "Rasam", "Butter milk", "Poriyal", "Kootu", "Appalam", "Pickle"],
  "Lunch 5": ["Sweet gulab jamun", "Payasam", "Vadai", "White Rice", "Sambar", "Kara kulambu", "Rasam", "Butter milk", "Poriyal", "Varuval", "Appalam", "Pickle"],
  "Lunch 6": ["Gulab jamun", "Chapati", "Channa masala", "Veg biryani", "Onion raita", "White Rice", "Sambar", "Vatha Kulambu", "Rasam", "Butter milk", "Poriyal", "Koottu", "Appalam", "Pickle"],
  "Lunch 7": ["Kaju Katli", "Fulka", "Channa masala", "Veg pulao", "Onion raita", "Bisibelabath", "White Rice", "Kara Kulambu", "Rasam", "Butter milk", "Poriyal", "Varuval", "Appalam", "Pickle"],
  "Lunch 8": ["Rasagulla", "Idiyappam", "Veg Paya", "Ghee rice", "Onion raita", "White Rice", "Paruppu podi & Ghee", "Sambar", "Moor Kulambu", "Rasam", "Varuval", "Poriyal", "Appalam", "Pickle"],
  "Lunch 9": ["Ghee Mysore pak", "Cauliflower 65", "Mushroom biryani", "Onion Raita", "White Rice", "Sambar", "Vatha Kulambu", "Rasam bath", "Curd rice", "Poriyal", "Varuval", "Koottu", "Vathal", "Pickle"],
  "Lunch 10": ["Agra pan", "Cutlet", "Sauce", "Veg dam Biryani", "Onion raita", "White Rice", "Paruppu podi & Ghee", "Kara kulambu", "Rasam", "Bisibela bath", "Bagala bath", "Potato Podi mass", "Chips", "Pickle"],
  "Lunch 11": ["Milk Payasam", "Vadai", "Chapati", "Paneer Butter Masala", "Brinji", "Raita", "Sambar rice", "Curd rice", "White Rice", "Vatha kulambu", "Rasam", "Appalam", "Pickle"],
  "Lunch 12": ["Gulabjamun", "Parippu pradhaman", "Mint rice", "White rice", "Dal & Ghee", "Vatha kulambu", "Kadhamba sambar", "Tomato rasam", "Curd", "National poriyal", "Brinjal Mochai Chops", "Appalam", "Mango pickle"],
  "Lunch 13": ["Jangiri", "Adai Pradhaman", "Special Vadai", "Mint Rice", "White Rice", "Dal & Ghee", "Kadhamba Sambar", "Vatha Kulambu", "Tomato Rasam", "Buttermilk", "National Poriyal", "Brinjal Mochai Chops", "Appalam", "Pickle"],
  "Lunch 14": ["Sweet Poli", "Adai Pradhaman", "Chapati", "Paneer pepper", "Masala", "Vegetable Pulao", "Raita", "White Rice", "Sambar", "Rasam", "Curd (Cup)", "Malabar Aviyal", "Carrot Poriyal", "Potato Chips", "Appalam", "Pickle"],
  "Lunch 15": ["Laddu", "Semiya Payasam", "White Pulao", "Cucumber curd", "pachadi", "White Rice", "Paruppu Podi & ghee", "Drumstick sambar", "Vatha kulambu", "Tomato rasam", "Chow Chow kootu", "Chepangilangu fry", "Butter Milk", "National poriyal", "Appalam", "Pickle"],
  "Lunch 16": ["Rasamalai", "Siru paruppu", "Payasam", "Curd Vadai", "Veg vanjaram fry", "Veg Brinji", "Onion Raita", "Bisi bele Bath", "Bagala Bath", "White Rice", "Kara kulambu", "Pepper Rasam", "Potato Fry", "Malabar Aviyal", "Mint Thuvaiyal", "Appalam", "Pickle"],
  "Lunch 17": ["Makkan Peda", "Aval payasam", "Special vadai", "Medhu Pakoda", "Veg prawn 65", "Chapati", "Kuruma", "Pulao", "White Rice", "Sambar", "Vatha kulambu", "Moor kulambu", "Rasam", "Aviyal", "Potato fry", "Appalam", "Inji Puli Pickle"],
  "Lunch 18": ["Malai Sandwich", "Badham Halwa", "Milk Payasam", "Masala Vadai", "Paneer tikka", "Palakai biryani", "Curd Pachadi", "Fulka", "Special Kuruma", "Vegetable Ghee Rice", "White Rice", "Small Onion Sambar", "Veg meen kulambu", "Pepper Rasam", "Curd", "Mor milagai", "Appalam", "Pickle"],
  "Lunch 19": ["Dry fruit halwa", "Gulab jamun", "Rice Payasam", "Special vadai", "Veg vanjaram fry", "Veg prawn fry", "Veg cutlet", "Cashew Pulao", "Kuruma", "Veg mutton Biryani", "Bunthi curd pachadi", "White Rice", "Sambar", "Rasam", "Butter milk", "Beans usili", "Baby Potato curry", "Appalam", "Pickle"],
  "Lunch 20": ["Kaju Katli", "Adai Pradhaman", "Cutlet", "Paniyaram", "Chutney", "Gobi Manchurian", "Rumali Roti", "Kadai Paneer", "Vegetable Ghee Rice", "Raita", "Bisi Bele Bath", "Bagala Bath", "Rasam Bath", "Senai Chops", "Vazhakkai Podimas", "Potato Beans Varuval", "Ginger Pickle", "Appalam", "Mor Milagai"]
};

export const DINNER_MENUS = {
  "Dinner 1": ["Gulab Jamun", "Gobi 65", "Veg Biryani", "Onion Raita", "Phulka", "Chana masala", "Bisi bele bath", "Bagalabath", "Potato Chips", "Mango Pickle"],
  "Dinner 2": ["Angoori Rasamalai", "Baby Corn 65", "Poori", "Chana masala", "Idiyappam", "White Kuruma", "Heart Idli", "Kara Chutney", "Tiffin Sambar", "JackFruit Biryani", "Cucumber Onion Raita"],
  "Dinner 3": ["Makkan Peda", "Veg Cutlet", "Idli", "Tiffin Sambar", "JackFruit Biryani", "Onion raita", "Bisi bele bath", "Bagalabath", "Poriyal", "Veg Varuval", "Appalam", "Mango Pickle"],
  "Dinner 4": ["Kaju katli", "Veg Roll", "Mushroom Biryani", "Onion Raita", "White Rice", "Sambar", "Vatha kuzhambu", "Rasam", "Poriyal", "Veg Varuval", "Appalam", "Mango Pickle"],
  "Dinner 5": ["Dry Fruit Burfi", "Lichi Rabdi", "Veg Roll", "Veg Vanjaram Fry", "Naan", "Malai Kofta", "Veg Dum Biryani", "Onion raita", "Bisi bele bath", "White Rice", "Poondu kulambu", "Pepper Rasam", "Curd Rice", "Poriyal", "Veg Varuval", "Appalam", "Mango Pickle"],
  "Dinner 6": ["Rasgulla", "Aval Payasam", "Hara bara Kabab", "Veg Chicken Tikka", "Coin Parotta", "Veg Salna", "Idiyappam", "Special Kuruma", "Veg Noodles", "Tomato Sauce", "Mushroom Biryani", "Onion raita", "Bisi bele bath", "Bagalabath", "Poriyal", "Appalam", "Mango Pickle"],
  "Dinner 7": ["Rose Paneer Jamun", "Agra Pan", "Veg Prawn 65", "Veg Vanjaram Fry", "Veg Hydrabad Biryani", "Onion Raita", "Masal Dosai", "Mushroom Kothu Curry", "White rice", "Kadamba Sambar", "Vatha kuzhambu", "Tomato Rasam", "Mor Kuzhambu", "Poriyal", "Malabar Avial", "Potato Chips", "Mango Pickle"],
  "Dinner 8": ["Angoori Rasamalai", "Siruparuppu payasam", "Veg Chicken Tikka", "Veg Lollipop", "Veg Mutton biryani", "Cucumber Onion Raita", "Rumali Roti", "Special kuruma", "Noodles", "Tomato Sauce", "Bisi bele bath", "Curd Rice", "Rasam bath", "Poriyal", "Veg Varuval", "Potato Chips", "Mango Pickle"],
  "Dinner 9": ["Shahi Tukda", "Malpua", "Ada Prathaman", "Veg vanjaram Fry", "Paneer Tikka", "Veg Seraga Samma biryani", "Onion raita", "Onion Podi Uthappam", "Chettinad Mushroom gravy", "Idiyappam", "Veg kuruma", "White Rice", "Kadhamba Sambar", "Veg Fish Kuzhambu", "Tomato Rasam", "Butter milk", "Potato fry", "Cabbage kootu", "Appalam", "Mango Pickle"],
  "Dinner 10": ["Sweet Agra pan", "Mini Jangiri", "Paruppu Payasam", "Mundhiri Pokoda", "Veg Many bag", "Veg Pulao", "Onion Raita", "Mini Dosai", "Tomato chutney", "Coconut Chutney", "Chapati", "Kadai Paneer", "Curd rice", "Bisi bele bath", "White rice", "Pepper Rasam", "Mor Kuzhambu", "National Poriyal", "Potato Chips", "Mango Pickle"],
  "Dinner 11": ["Malpua Rabdi", "Makkan Peda", "Vetrilai Payasam", "Veg Vanjaram Fry", "Sweet Potato Fry", "Stuffed Parotta", "Special Kuruma", "Jackfruit biryani", "Onion raita", "Podi Dosai", "Mushroom Kothu Curry", "Bisi bele bath", "Curd Rice", "Vatha Kuzhambu Rice", "BagalaBath", "Malabar Aviyal", "Poriyal", "Veg Varuval", "Appalam", "Mango Pickle"],
  "Dinner 12": ["Rasmalai", "Kaju Katli", "Elaneer Payasam", "Sweet Corn Pepper Fry", "Veg Chicken Tikka", "Veg Mutton Biryani", "Onion Raita", "Chapati", "Paneer Butter Masala", "Coin Parotta", "Veg paya", "Veg noodles", "Tomato sauce", "Bisi bele bath", "Curd rice", "Veg Pulao", "White rice", "Tomato Rasam", "National Poriyal", "Potato Chips", "Mango Pickle"],
  "Dinner 13": ["Rasagulla", "Baklava", "Elaneer payasam", "Gobi 65", "Hara Bara Kabab", "Veg Kola Urundai", "Seeraga Samba biryani", "Onion raita", "Rumali roti", "Paneer butter masala", "Idiyappam", "Veg paya", "White rice", "Sambar", "Veg Prawn Thokku", "Tomato Rasam", "Butter milk", "Potato peas varuval", "National Poriyal", "Appalam", "Potato Chips", "Mango Pickle"],
  "Dinner 14": ["Makkan Peda", "Elaneer payasam", "Malai sandwich", "Veg Chicken Tikka", "Veg Vanjaram Fry", "Veg Kola Urundai", "Veg Mutton biryani", "Onion raita", "Idiyappam", "Kuruma", "Rumali roti", "Channa masala", "Bisi bele bath", "White rice", "Vatha kuzhambu", "Tomato Rasam", "Butter milk", "Veg Corn Poriyal", "Potato peas Varuval", "Malabar Avial", "Appalam", "Mango Pickle"],
  "Dinner 15": ["Kaju katli", "Elaneer payasam", "Rasmalai", "Gobi Manjurian", "Veg Vanjaram fry", "Vazaipoo Vadai", "Mushroom biryani", "Onion raita", "Rumali roti", "Paneer butter masala", "Idiyappam", "Special Veg kuruma", "Veg Noodles", "Tomato sauce", "White rice", "Sambar", "Veg Fish kuzhambu", "Rasam", "Butter milk", "Poriyal", "Veg Varuval", "Kootu", "Appalam", "Mango Pickle"],
  "Dinner 16": ["Agra Pan", "Rasmalai", "Makkan Peda", "Cashew Pakoda", "Veg Prawn 65", "Veg Chicken Tikka", "Phulka", "Paneer Butter masala", "Veg Noodles", "Tomato Sauce", "Veg Mutton biryani", "Onion raita", "Bisi bele bath", "Curd Rice", "White Rice", "Vatha kuzhambu", "Paruppu Rasam", "Buttermilk", "Malabar Aviyal", "Potato Curry", "Potato Chips", "Appalam", "Mango Pickle"],
  "Dinner 17": ["Malai Sandwich", "Elaneer payasam", "Malpua", "Paneer tikka", "Gobi Manjurian", "Veg vanjaram Fry", "Square chapatis", "Veg Kuruma", "Veg Mutton biryani", "Onion Raita", "Parotta", "Cashew Pepper Gravy", "Idiyappam", "Veg Fish Kuzhambu", "Veg Noodles", "Tomato sauce", "Bisi bele bath", "Bagalabath", "Rasam bath", "Potato Chips", "Appalam", "Mango Pickle"],
  "Dinner 18": ["Sweet lichi rabdi", "Agra Pan", "Elaneer payasam", "Veg vanjaram fry", "Veg prawn fry", "Gobi Manjurian dry", "Idiyappam", "Chana masala", "Phulka", "Paneer butter masala", "Onion uttapam", "Tomato chutney", "Sambar", "Mushroom biryani", "Onion Raita", "Bisi bele Bath", "Rasam Bath", "Curd rice", "National poriyal", "Appalam", "Mango Pickle"],
  "Dinner 19": ["Dry Fruit Burfi", "Hot Badam milk", "Bundhi Ladoo", "Veg Roll", "Veg Cutlet", "Kara Paniyaram", "Bun parotta", "Veg Mutton biryani", "Onion raita", "Phulka", "Kadai Paneer", "Idiyappam", "Veg paya", "Veg Noodles", "Tomato sauce", "Bisi bele Bath", "White rice", "Vatha kuzhambu", "Rasam", "Curd rice", "National Poriyal", "Potato beas Varuval", "Potato Chips", "Appalam", "Mango Pickle"],
  "Dinner 20": ["Makkan peda", "Elaneer payasam", "Agrapan", "Veg Chicken Tikka", "Veg Prawn 65", "Veg Corn Nuggets", "Rumali roti", "Paneer butter masala", "Veg mutton biryani", "Onion raita", "Veg Noodles", "Tomato sauce", "Onion Uthappam", "Coconut chutney", "Kara chutney", "Bisi bele Bath", "Curd rice (With Fruits)", "White rice", "Vatha kuzhambu", "Rasam", "Potato beas Varuval", "Malabar Avial", "Appalam", "Mango Pickle"],
  "Dinner 21": ["Rasmalai", "Elaneer payasam", "Sweet Badham roll", "Veg Vanjaram fry", "Gobi Manjurian", "Paneer Fingers", "Mushroom biryani", "Onion raita", "Rumali Roti", "Paneer butter masala", "Thattu idli", "Onion Uthappam", "Tiffin Sambar", "Kara chutney", "Coconut chutney", "Bisi bele Bath", "Curd rice", "White rice", "Rasam", "Potato beas Varuval", "Potato Chips", "Malabar Avial", "Appalam", "Mango Pickle"],
  "Dinner 22": ["Rasmalai", "Hot Jalebi", "Elaneer Payasam", "Paneer Tikka", "Manjurian Semi Gravy", "Rumali Roti", "Paneer butter masala", "Idiyappam", "Special Veg kuruma", "Masala Dosai", "Mushroom kothu curry", "Mushroom Biryani", "Onion Raita", "Veg Noodles", "Tomato sauce", "Bisibelebath", "Curd Rice", "White rice", "Rasam", "Vatha kuzhambu", "Malabar Avial", "Varuval", "Appalam", "Mango Pickle"],
  "Dinner 23": ["Rasmalai", "Malpua", "Carrot halva", "Veg Chicken Tikka", "Veg Lolli pop", "Veg Kola Urundai", "Bun parotta", "Cashew Gravy", "Jackfruit biryani", "Onion raita", "Onion Uthappam", "Tiffin Sambar", "Thattu Idli", "Coconut chutney", "Veg Fried Rice", "Tomato sauce", "Bisibelebath", "Curd Rice", "White rice", "Rasam", "Vatha kuzhambu", "Paruppu Rasam", "Potato Peas Varuval", "Malabar avial", "Appalam", "Mango Pickle"],
  "Dinner 24": ["Shahi tukda", "Kaju katli", "Paan Payasam", "Gobi 65", "Veg Cutlet", "Veg vanjaram fry", "Bun parotta", "Mushroom gravy", "Veg mutton biryani", "Onion raita", "Rumali roti", "Paneer butter masala", "Podi thattu idli", "Kara chutney", "Bisi bele bath", "White rice", "Vatha kuzhambu", "Rasam", "Butter milk", "Avial", "Kootu", "Urulai varuval", "Potato chips", "Appalam (Big size)", "Mango Pickle"],
  "Dinner 25": ["Rasmalai", "Agra pan", "Elaneer payasam", "Veg Chicken Tikka", "Veg Lolli pop", "Bun parotta", "Paneer butter masala", "Veg mutton biryani", "Onion raita", "Thattu idli", "Veg Fish kuzhambu", "Veg Fried rice", "Tomato sauce", "Rumali roti", "Channa masala", "Bisi bele bath", "White rice", "Vatha kuzhambu", "Rasam", "Butter milk", "Veg Prawn thokku", "National poriyal", "karunai chops", "Appalam", "Mango Pickle"],
  "Dinner 26": ["Gulab jamun", "Aval Payasam", "Rasmalai", "Thayir vadai", "Baby Corn 65", "Tamarind Rice", "Mango Rice", "Sambar Sadam", "Rasam Sadam", "Curd sadam", "Veg Biryani", "Curry Leaves Rice", "Lemon Rice", "Pudina Thogayal", "Potato Beas varuval", "National Poriyal", "Appalam"]
};

export const SMART_CHOICE_MENUS = {
  "Smart Choice M1": ["Gulab Jamun", "Gobi 65", "Onion Rings", "Veg Biryani", "Onion Raita", "Phulka", "Channa Masala", "Idiyappam", "Kurma", "Sambar Sadam", "Curd Rice", "Rasam Sadam", "Mixed Vegetable Poriyal", "Potato Varuval", "Neetu Appalam"],
  "Smart Choice M2": ["Kaju Katli", "Veg Cutlet", "Bread Chilli", "Mushroom Biryani", "Onion Raita", "Thattu Idli", "Onion Uttapam", "Tiffin Sambar", "Chutney", "Sambar Sadam", "Curd Rice", "Rasam Sadam", "Mixed Vegetable Poriyal", "Potato Varuval", "Neetu Appalam", "Mango Pickle"],
  "Smart Choice M3": ["Sweet Mango Roll", "Sweet Payasam", "Veg Chicken Tikka", "Veg Lollipop", "Veg Mutton Biryani", "Onion Raita", "Phulka", "Paneer Butter Masala", "Idiyappam", "Kuruma", "Bisi Bele Bath", "Rasam Sadam", "Curd Rice", "Corn Veg Poriyal", "Potato Varuval", "Appala Poo", "Pickles"],
  "Smart Choice M4": ["Angoor Rasmalai", "Veg Soup", "Veg Prawn 65", "Baby Corn Fry", "Veg Pulao", "Onion Raita", "Thattu Idli", "Onion Uthappam", "Coconut Chutney", "Kara Chutney", "Bisi Bele Bath", "Curd Rice", "Rasam Sadam", "Corn Veg Poriyal", "Potato Varuval", "Appala Poo", "Pickles"],
  "Smart Choice M5": ["Paneer Jamun", "Badam Milk (Hot/Cold)", "Veg Roll", "Ghee Rice", "Onion Raita", "Poori", "Channa Masala", "Mini Dosa", "Kalan Kothu Curry", "Bisi Bele Bath", "Curd Rice", "Rasam Sadham", "Corn Veg Poriyal", "Special Potato Varuval", "Appala Poo", "Pickles", "Veg Vanjaram Fry"]
};

export const CATEGORY_MENUS = {
  "Budget Sweets": ["Gulab Jamun", "Dry Gulab Jamun", "Panner Gulab Jamun", "Gulab Gulab Jamun", "Mini Badusha", "Rasgulla", "Khaja Sweet", "Rava Ladoo", "Mini Jangiri", "Ghee Mini Laddu", "Soan Papdi", "Rabdi Jalebi", "Elai Adai", "Paruppu Poli", "Coconut Poli"],
  "Premium Sweets": ["Mysore Pak", "Milk Cake", "Dry Fruit Barfi", "Malpua", "Ras Malai", "Moti Pak", "Malai Sandwich", "Strawberry Cham Cham", "Lychee Rabri", "Malai Roll", "Chandrakala", "Suryakala", "Basundi", "Strawberry Rasgulla", "Chocolate Burfi", "Pathir Pheni", "Kesar Angoori Pet"],
  "Luxury Sweets (1)": ["Watermelon Sweet", "Pista Katli", "Sweet Kunafa", "Pootharekulu", "Kunafa Finger", "Pista Kunafa", "Nutella Laddu", "Mango Rabri", "Chocolate Coconut Laddu", "Kaju Pista Roll", "Coconut Laddu"],
  "Luxury Sweets (2)": ["Kaju Katli", "Badam Roll", "Kaju Pista Roll", "Shahi Tukda", "Angoori Rasmalai", "Ghee Mysore Pak", "Agra Paan Sweet", "Mango Roll", "Rabdi Ghewar", "Nest Baklava", "Pistachio Baklava", "Pista Pyramid", "Baklava", "Dry Fruit Tart Baklava", "Rose Delight Sweet", "Kaju Anarkali"],
  "Halwa Varieties": ["Gulab Jamun", "Carrot Halwa", "Kasi Halwa", "Badam Halwa", "Karupatti Halwa", "Kavuni Arisi Halwa", "Milk Halwa", "Ashoka Halwa", "Tirunelveli Halwa", "Bombay Halwa", "Beetroot Halwa", "Banana Halwa", "Mango Halwa", "Jackfruit Halwa", "Pineapple Halwa", "Dry Fruit Halwa", "Dates Halwa", "Cashew Halwa", "Coconut Halwa", "Suji Ka Halwa", "Chocolate Halwa", "Maravalli Kizhangu Halwa", "Kerala Black Halwa", "Green Moong Dal Halwa", "Moong Dal Halwa", "Apple Halwa", "Rose Halwa"],
  "Payasam Varieties": ["Paal Payasam", "Paruppu Payasam", "Vetrilai Payasam", "Elaneer Payasam", "Caramel Payasam", "Paal Paniyaram", "Paal Kozhukattai", "Badam Paal", "Dates Kheer", "Pazham Pradhaman", "Semiya Payasam", "Aval Payasam", "Javvarisi Payasam", "Ada Pradhaman", "Palada Payasam", "Kambu Payasam", "Rava Payasam", "Badam Kheer", "Wheat Payasam", "Millet Payasam", "Dry Fruit Payasam", "Coconut Payasam", "Karupatti Payasam", "Jaggery Payasam", "Jackfruit Payasam", "Mango Payasam", "Ragi Kheer", "Carrot Kheer"],
  "Kesari Varieties": ["Rava Kesari", "Semiya Kesari", "Aval Kesari", "Wheat Rava Kesari", "Carrot Kesari", "Beetroot Rava Kesari", "Banana Kesari", "Orange Rava Kesari", "Apple Kesari", "Rose Rava Kesari", "Pineapple Kesari", "Mango Kesari", "Fruit Kesari", "Milk Kesari", "Jackfruit Kesari", "Strawberry Kesari", "Coconut Milk Kesari", "Chocolate Kesari", "Badam Kesari", "Kiwi Kesari", "Grapes Kesari"],
  "Juice Varieties": ["Musk Melon Juice", "Watermelon Juice", "Watermelon-Mint Juice", "Sathukudi Juice", "Grape Juice", "Mint Lemonade", "Sweet Lime Mint Juice", "Orange Juice", "Apple Juice", "Mixed Fruit Juice", "Pineapple Juice", "Carrot Juice", "Beet Juice", "Papaya Juice", "Guava Juice", "Jigarthanda", "Nannari Sharbat", "Tender Coconut Juice", "Mint Soda", "Fresh Lime Soda", "Mojito (Non-alcoholic)", "Lychee Juice", "Rose Milk", "Badam Milk", "Nungu Sarbath", "Nungu Milkshake", "Musk Melon Milkshake", "Strawberry Milkshake", "Banana Milkshake", "Chikoo Milkshake", "Dry Fruit Milkshake", "Falooda", "Blue Lagoon Mocktail", "Pomegranate Juice"],
  "Budget Starters": ["Gobi 65", "Gobi Manchurian", "Baby Corn 65", "Crispy Corn", "Veg Spring Roll", "Veg Cutlet", "Potato Pepper Fry", "French Fries", "Veg Nuggets", "Onion Pakora", "Veg Pakora", "Veggie Balls"],
  "Premium Starters": ["Paneer 65", "Paneer Manchurian", "Chilli Paneer", "Veg Money Bag", "Veg Lollipop", "Golden Fried Baby Corn", "Baby Corn Pepper Fry", "Mushroom 65", "Mushroom Pepper Fry", "Corn Cheese Balls", "Corn Cheese Nuggets", "Cheese Stuffed Roll", "Crispy Paneer Fingers", "Veg Seekh Kabab", "Hara Bhara Kabab", "Tandoori Aloo", "Veg Momos", "Dragon Paneer"],
  "Luxury Starters": ["Paneer Tikka", "Tandoori Paneer", "Veg Tandoori Platter", "Veg Tandoori Momos", "Stuffed Paneer Tikka", "Grilled Veg Skewers", "Cheese Corn Shots", "Crispy Honey Chilli Potato", "Tandoori Baby Corn", "Achari Mushroom Tikka", "Achari Paneer Tikka", "Hariyali Paneer Tikka", "Malai Veg Seekh Kabab", "Paneer Lollipop", "Cheese Balls"],
  "Veg To Non Veg Items": ["Veg Prawn 65", "Veg Vanjaram Fish Fry", "Veg Chicken Tikka", "Veg Chicken Keema", "Veg Chicken 65", "Veg Chicken Thokku", "Veg Fish Kulambu", "Veg Mutton Keema", "Veg Fish Finger", "Veg Sura Puttu", "Veg Eral Thokku", "Veg Mutton Sukka"],
  "Soup Varieties": ["Sweet Corn Soup", "Tomato Soup", "Cream of Tomato Soup", "Cream of Mushroom Soup", "Paneer Soup", "Hot & Sour Soup", "Manchow Soup", "Carrot Soup", "Mixed Vegetable Soup", "Creamy Vegetable Soup", "Baby Corn Soup", "Green Peas Soup"],
  "Sabzi Varieties": ["Chana Masala", "Paneer Butter Masala", "Kadai Paneer", "Veg Paya", "Veg Special Kurma", "Kaju Masala", "Malai Kofta", "Mushroom Pepper Masala", "Madurai Style Veg Salna", "Veg Stew", "Vada Curry", "Poori Masala", "Paneer Tikka Masala", "Shahi Paneer", "Mushroom Masala", "Chettinad Mushroom", "Mushroom Kurma", "Aloo Gobi Masala", "Aloo Capsicum Masala"],
  "Poriyal Varieties": ["Cabbage Poriyal", "Beans Poriyal", "Carrot Poriyal", "Beetroot Poriyal", "Potato Poriyal", "Vazhakkai Poriyal", "Mixed Vegetable Poriyal", "Kathirikai Poriyal", "Capsicum Poriyal", "Corn Poriyal", "Cauliflower Poriyal", "Green Peas Poriyal", "Cabbage Carrot Poriyal", "Carrot Beans Poriyal", "Snake Gourd Poriyal (Pudalangai)", "Mullangi Poriyal", "Neetu Appalam", "Round Appalam"],
  "Kootu Varieties": ["Poricha Kootu", "Mixed Vegetable Kootu", "Pumpkin Kootu", "Sorakkai Kootu", "Chow Chow Kootu", "Vendakkai Kootu", "Cabbage Kootu", "Paruppu Kootu", "Cauliflower Potato Kootu", "Vazhaithandu Kootu", "Vazhakkai Kootu", "Pudalangai Kootu", "Kathirikai Kootu", "Beans Kootu", "Carrot Kootu", "Peerkangai Kootu", "Mullangi Kootu", "Senai Kizhangu Kootu", "Pachai Payaru Masiyal", "Mochai Kootu", "Cowpea Kootu (Karamani)", "Mixed Dal", "Coconut Milk Vegetable Kootu"],
  "Varuval Varieties": ["Cauliflower Varuval", "Potato Varuval", "Vazhakkai Varuval", "Senai Kizhangu Varuval", "Mushroom Varuval", "Paneer Varuval", "Baby Corn Varuval", "Beetroot Varuval", "Cabbage Varuval", "Kathirkai Varuval", "Vendakkai Varuval", "Kondakadalai Varuval", "Green Peas Varuval", "Soya Chunks Fry", "Karamani Varuval", "Thamarai Thandu Varuval", "Capsicum Fry"],
  "Special Combo Varieties": ["Veg Pulao", "Beetroot Pulao", "Kashmiri Pulao", "Panner Pulao", "Sweet Corn Pulao", "Spicy Vegetable pulao", "Veg Biryani", "Paalakai Biryani", "Veg Mutton Biryani", "Veg Prawn 65 Biryani", "Cauliflower Biryani", "Paneer Biryani", "Baby Corn Biryani", "Jeera Ghee Rice", "Coconut Milk Rice", "Veg Noodles", "Schezwan Noodles", "Mushroom Noodles", "Paneer Noodles", "Veg Fried Rice", "Schezwan Fried Rice", "Mushroom Fried Rice", "Paneer Fried Rice", "Baby Corn Fried Rice", "Sweet Corn Fried Rice"],
  "Mixed Rice Varieties": ["Lemon Rice", "Tomato Rice", "Tamarind Rice (Puliyodhorai)", "Coconut Rice", "Curd Rice", "Veg Fried Rice", "Schezwan Fried Rice", "Mushroom Fried Rice", "Paneer Fried Rice", "Baby Corn Fried Rice", "Mixed Veg Rice", "Sambar Rice", "Rasam Rice", "Bisi Bele Bath", "Jeera Rice", "Ghee Rice", "Mint Rice (Pudina Rice)", "Coriander Rice", "Spinach Rice", "Coconut Milk Rice", "Curry Leaf Rice", "Carrot Rice", "Beetroot Rice", "Capsicum Rice", "Peas Rice", "Garlic Rice", "Sweet Corn Rice", "Veg Biriyani", "Paneer Biriyani", "Mushroom Biriyani"],
  "Kuzhambu Varieties": ["Arachuvitta Sambar", "Kerala Sambar", "Udupi Sambar", "Mysore Sambar", "Andhra Sambar", "Tiffin Sambar", "Classic Sambar", "Drumstick Sambar", "Brinjal Sambar", "Small Onion Sambar", "Mango Sambar", "Carrot Sambar", "Raw Mango Rasam", "Pineapple Rasam", "Mysore Rasam", "Mixed Vegetable Sambar", "Mor Kulambu", "Vatha Kulambu", "Kathirikai Kara Kuzhambu", "Vendakkai Kara Kuzhambu", "Poondu Kuzhambu", "Paruppu Urundai Kuzhambu", "Karuveppilai Kuzhambu", "Manathakkali Vathal Kulambu", "Jeera Rasam", "Sundakkai Vathal Kuzhambu", "Pavakkai Puli Kuzhambu", "Mochakottai Kuzhambu", "Kothavarangai Kara Kulambu", "Inji Kuzhambu", "Milagu Kulambu", "Tomato Rasam", "Pepper Rasam", "Lemon Rasam", "Garlic Rasam", "Paruppu Rasam"],
  "Idiyappam Varieties": ["Plain Idiyappam", "Coconut Idiyappam", "Sweet Jaggery Idiyappam", "Veg Masala Idiyappam", "Ghee Idiyappam", "Butter Idiyappam", "Chilli Idiyappam", "Milk Idiyappam", "Vegetable Kothu Idiyappam", "Spinach (Palak) Idiyappam", "Mixed Veg Idiyappam", "Masala Kothu Idiyappam"],
  "Parotta Varieties": ["Plain Parotta", "Malabar Parotta", "Wheat Parotta", "Small Mini Parotta", "Coin Parotta", "Bun Parotta", "Kerala Layer Parotta", "Veechu Parotta", "Stuffed Parotta", "Cheese Stuffed Parotta", "Chilli Parotta", "Kothu Parotta", "Ragi Parotta", "Multigrain Parotta", "Millet Parotta"],
  "Chapati Varieties": ["Plain Chapati", "Soft Chapati", "Wheat Chapati", "Butter Naan", "Fulka", "Rumali Roti", "Multigrain Chapati", "Aloo Stuffed Chapati", "Paneer Stuffed Chapati", "Corn Chapati", "Mixed Veg Stuffed Chapati", "Cheese Stuffed Chapati", "Mushroom Stuffed Chapati", "Ghee Chapati", "Butter Chapati", "Ragi Chapati", "Pearl millet Chapati"],
  "Dosai & Uthappam Varieties": ["Plain Dosa", "Ghee Dosa", "Butter Dosa", "Masala Dosa", "Onion Dosa", "Rava Dosa", "Rava Onion Dosa", "Set Dosa", "Kal Dosa", "Paper Roast", "Podi Dosa", "Ghee Podi Dosa", "Mysore Masala Dosa", "Cheese Dosa", "Paneer Dosa", "Tomato Dosa", "Carrot Dosa", "Corn Cheese Dosa", "Mushroom Dosa", "Schezuan Dosa", "Sweet Dosa", "Spinach / Palak Dosa", "Ragi Dosa", "Wheat Dosa", "Kambu (Bajra) Dosa", "Thinai (Foxtail Millet) Dosa", "Varagu (Kodo Millet) Dosa", "Samai (Little Millet) Dosa", "Multi Millet Dosa", "Chinese Dosa", "Tandoori Dosa", "Pizza Dosa", "Chocolate Dosa", "Plain Uthappam", "Onion Uthappam", "Tomato Uthappam", "Mixed Veg Uthappam", "Carrot Uthappam", "Capsicum Uthappam", "Onion Tomato Uthappam", "Paneer Uthappam", "Cheese Uthappam", "Podi Uthappam", "Ghee Uthappam", "Mysore Uthappam", "Ragi Uthappam", "Wheat Uthappam", "Millet Uthappam", "Appam", "Shiva Parasi Appam", "Elaneer Appam"],
  "Idli Varieties": ["Plain Idli", "Mini Idli", "Rava Idli", "Kanchipuram Idli", "Malligai Poo Idli / Soft Idli", "Button Idli", "Podi Idli", "Ghee Podi Idli", "Garlic Podi Idli", "Pepper Idli", "Curry Leaves Idli", "Carrot Idli", "Beetroot Idli", "Spinach Idli", "Tomato Idli", "Fry Idli", "Chilli Idli", "Schezwan Idli", "Masala Idli", "Tawa Idli", "Butter Idli", "Heartin Idli", "Red Rice Idli", "Star Idli", "Foxtail Millet Idli", "Varagu Millet Idli", "Little Millet Idli", "Multi Millet Idli", "Oats Idli", "Thanjavur Idli", "Millet Idli", "Ragi Idli", "Green Gram Idli"],
  "Pongal Varieties": ["Ven Pongal", "Sarkarai Pongal", "Milagu Pongal", "Ghee Pongal", "Rava Pongal", "Samba Pongal", "Thinai Pongal", "Kambu Pongal", "Ragi Pongal", "Samai Pongal", "Varagu Pongal", "Red Rice Pongal", "Moong Dal Pongal", "Tomato Pongal", "Pal Pongal", "Sathu Maavu Pongal", "Gothumai Pongal"],
  "Poori & Semiya Varieties": ["Wheat Poori", "Rava Poori", "Chola poori", "Paneer Stuffed Poori", "Aloo Stuffed Poori", "Beetroot Poori", "Carrot Poori", "Semiya sevai", "Semiya Upma", "Semiya Khichadi", "Semiya Pongal", "Semiya Biryani", "Semiya Pulav", "Thayir Semiya", "Semiya Tomato Bath", "Semiya Vegetable Masala"],
  "Adai Varieties": ["Mixed Lentil Adai", "Ilai Adai", "Ragi Adai", "Kambu Adai", "Jowar Adai", "Drumstick Leaves Adai", "Spinach Adai", "Onion Adai", "Aval Adai", "Carrot Adai", "Coriander Leaves Adai", "Tomato Adai", "Black Gram Adai", "Green Gram Adai", "Sweet Adai"],
  "Paniyaram Varieties": ["Kara Paniyaram", "Sweet Paniyaram", "Karupatti Paniyaram", "Masala Paniyaram", "Milagu Paniyaram", "Onion Paniyaram", "Vegetable Paniyaram", "Coriander Paniyaram", "Curry Leaves Paniyaram", "Tomato Paniyaram", "Mint Paniyaram", "Ginger Paniyaram", "Rava Paniyaram", "Wheat Paniyaram", "Ragi Paniyaram", "Kambu Paniyaram", "Thinai Paniyaram", "Aval Paniyaram", "Banana Sweet Paniyaram", "Jaggery Paniyaram", "Chettinad Kara Paniyaram", "Butter Paniyaram", "Coconut Paniyaram"],
  "Rava Varieties": ["Rava Upma", "Rava Khichdi", "Rava Pongal", "Rava Dosa", "Rava Roti", "Rava Idli", "Rava Paniyaram", "Rava Poori", "Rava Idiyappam", "Rava Vegetable Bath", "Masala Rava Upma", "Lemon Rava Upma", "Tomato Rava Upma"]
};
