with:
  host: ${{ secrets.HOST }}
  username: ${{ secrets.USERNAME }}
  key: ${{ secrets.SSH_KEY }}
  port: 22
  script: |
    set -e
    cd ${{ secrets.TARGET_DIR }}

    git pull origin main

    docker compose down
    docker compose up -d --build

    docker image prune -f